name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Unzip
        run: unzip -o ruleta-mod.zip

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.10.2

      - name: Compile
        working-directory: ruleta-mod
        run: gradle build --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: ruleta-mod
          path: |
            ruleta-mod/build/libs/*.jar
            !ruleta-mod/build/libs/*-sources.jar
